site_name: Documentation
docs_dir: src
site_dir: docs
dev_addr: 0.0.0.0:4000
theme:
  name: material
  custom_dir: theme
  palette:
    primary: black
    accent: red
  logo: assets/images/logo.min.svg
  favicon: assets/images/favicon.ico
extra_css:
  - assets/css/styles.css
nav:
  - Introduction: "README.md"
  - DCI RHEL Agent:
      - Installation: "dci-rhel-agent/README.md"
      - Beaker installation: "ansible-playbook-dci-beaker/README.md"
      - RHEL version support: "dci-rhel-agent/docs/support.md"
  - DCI OpenStack Agent:
      - Installation: "dci-openstack-agent/README.md"
      - Advanced: "dci-openstack-agent/docs/advanced.md"
      - Certification: "dci-openstack-agent/docs/certification.md"
      - RHOSP version support: "dci-openstack-agent/docs/support.md"
  - DCI OpenShift Agent:
      - Installation: "dci-openshift-agent/README.md"
      - Libvirt environment: "dci-openshift-agent/docs/ocp_on_libvirt.md"
      - Disconnected environment: "dci-openshift-agent/docs/disconnected_en.md"
      - Development: "dci-openshift-agent/docs/development.md"
      - RHOCP version support: "dci-openshift-agent/docs/support.md"
  - DCI OpenShift App Agent: "dci-openshift-app-agent/README.md"
  - DCI Downloader: "dci-downloader/README.md"
  - DCI CLI: "python-dciclient/README.md"
  - DCI API: "dci-control-server/docs/API.md"
  - Contribute:
      - dci-control-server: "dci-control-server/README.md"
      - dci-ui: "dci-ui/README.md"
      - dci-auth: "python-dciauth/README.md"
  - Questions and help: "question_and_help.md"
