site_name: Documentation
docs_dir: build
site_dir: docs
dev_addr: 127.0.0.1:4000
theme:
  name: material
  custom_dir: theme
  palette:
    primary: black
    accent: red
  logo: assets/images/logo.min.svg
  favicon: assets/images/favicon.ico
extra_css:
  - assets/css/styles.css
nav:
  - Introduction: "README.md"
  - General Concepts: "general_concepts.md"
  - Get started: "get_started.md"
  - DCI RHEL Agent:
      - Installation: "dci-rhel-agent/README.md"
      - RHEL version support: "dci-rhel-agent/docs/support.md"
  - DCI OpenStack Agent:
      - Installation: "dci-openstack-agent/README.md"
      - Advanced: "dci-openstack-agent/docs/advanced.md"
      - Certification: "dci-openstack-agent/docs/certification.md"
      - RHOSP version support: "dci-openstack-agent/docs/support.md"
  - DCI OpenShift Agent:
      - Installation: "dci-openshift-agent/README.md"
      - Alternate installation methods:
          - User Provisioned Infrastructure: "dci-openshift-agent/docs/upi.md"
          - Agent Based Installer: "dci-openshift-agent/docs/abi.md"
          - Advanced Cluster Management (ACM): "dci-openshift-agent/docs/acm.md"
          - GitOps ZTP based installation: "dci-openshift-agent/docs/gitops-ztp.md"
          - Assisted Installer on-prem (deprecated): "dci-openshift-agent/docs/ai-on-prem-deprecation.md"
      - Libvirt environment: "dci-openshift-agent/docs/ocp_on_libvirt.md"
      - Disconnected environment: "dci-openshift-agent/docs/disconnected_en.md"
      - Development: "dci-openshift-agent/docs/development.md"
      - RHOCP version support: "dci-openshift-agent/docs/support.md"
  - DCI OpenShift App Agent: "dci-openshift-app-agent/README.md"
  - DCI Downloader: "dci-downloader/README.md"
  - DCI CLI: "python-dciclient/README.md"
  - DCI Pipeline/Queue: "dci-pipeline/README.md"
  - DCI Ansible: "dci-ansible/README.md"
  - DCI API: "dci-control-server/docs/API.md"
  - Contribute:
      - dci-control-server: "dci-control-server/README.md"
      - dci-ui: "dci-ui/README.md"
      - dci-auth: "python-dciauth/README.md"
  - Questions and help: "question_and_help.md"
